In [2]:
import os
import sys
from pathlib import Path

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import nvitk.core as core

In [11]:
print(core.get_global_backend())
core.setup(globals())

print(core.available_backends())

numpy
('numpy', 'cupy')


In [16]:
core.set_global_backend('gpu')
print(np.__version__, np.__name__)

arr = np.array([1, 2, 3])
print(arr, type(arr))

with core.using('cpu'):
    arr = core.as_backend_array(arr)
    print(np.__version__, np.__name__)
    print(arr, type(arr))

arr = core.as_backend_array(arr)
print(arr, type(arr))

13.6.0 cupy
[1 2 3] <class 'cupy.ndarray'>
2.3.3 numpy
[1 2 3] <class 'numpy.ndarray'>
[1 2 3] <class 'cupy.ndarray'>


In [10]:
core.set_global_backend('cpu')
print(core.get_global_backend())

numpy
